-- ============================================================================
-- JOINSTICK Stage Demo — Supabase schema
-- ----------------------------------------------------------------------------
-- Run this file top-to-bottom in the Supabase SQL Editor.
-- The script is IDEMPOTENT: re-running it is safe (create if not exists,
-- drop policy if exists before create, realtime additions wrapped in DO
-- blocks that ignore duplicate_object errors).
--
-- Tables:
--   demo_sessions          - one row per stage-demo session (QR code, phase)
--   demo_participants      - one row per device that joined a session
--   demo_harvester_answers - Harvester mini-survey answers (rating 0-4)
--   demo_survey_responses  - final satisfaction survey (rating 1-5 + comment)
--   demo_events            - raw event log (join / completes / step changes)
-- ============================================================================

create extension if not exists pgcrypto;

-- ----------------------------------------------------------------------------
-- 1) demo_sessions
-- ----------------------------------------------------------------------------
create table if not exists public.demo_sessions (
  id               uuid primary key default gen_random_uuid(),
  code             text unique not null,
  name             text not null default 'Stage Demo',
  phase            text not null default 'demo'
                     check (phase in ('demo', 'eyes_up', 'survey')),
  is_active        boolean not null default true,
  created_at       timestamptz default now(),
  phase_changed_at timestamptz default now()
);

-- ----------------------------------------------------------------------------
-- 2) demo_participants
--    UNIQUE(session_id, device_id) is REQUIRED — the apps upsert with
--    onConflict: 'session_id,device_id'.
-- ----------------------------------------------------------------------------
create table if not exists public.demo_participants (
  id           uuid primary key default gen_random_uuid(),
  session_id   uuid not null references public.demo_sessions (id) on delete cascade,
  device_id    text not null,
  nickname     text,
  current_step text not null default 'join',
  user_agent   text,
  joined_at    timestamptz default now(),
  last_seen_at timestamptz default now(),
  unique (session_id, device_id)
);

-- ----------------------------------------------------------------------------
-- 3) demo_harvester_answers
--    UNIQUE(participant_id, question_id) is REQUIRED — the apps upsert with
--    onConflict: 'participant_id,question_id'.
-- ----------------------------------------------------------------------------
create table if not exists public.demo_harvester_answers (
  id             bigint generated by default as identity primary key,
  session_id     uuid references public.demo_sessions (id) on delete cascade,
  participant_id uuid references public.demo_participants (id) on delete cascade,
  question_id    text not null,
  question_text  text not null,
  rating         smallint not null check (rating between 0 and 4),
  created_at     timestamptz default now(),
  unique (participant_id, question_id)
);

-- ----------------------------------------------------------------------------
-- 4) demo_survey_responses
--    UNIQUE(participant_id) is REQUIRED — the apps upsert with
--    onConflict: 'participant_id'.
-- ----------------------------------------------------------------------------
create table if not exists public.demo_survey_responses (
  id             bigint generated by default as identity primary key,
  session_id     uuid references public.demo_sessions (id) on delete cascade,
  participant_id uuid references public.demo_participants (id) on delete cascade,
  rating         smallint not null check (rating between 1 and 5),  -- Q1: satisfaction
  rating2        smallint check (rating2 between 1 and 5),           -- Q2: Behavior Transformation
  comment        text,
  created_at     timestamptz default now(),
  unique (participant_id)
);

-- rating2 added after launch — ensure it exists on already-created tables too
alter table public.demo_survey_responses
  add column if not exists rating2 smallint check (rating2 between 1 and 5);

-- ----------------------------------------------------------------------------
-- 5) demo_events
-- ----------------------------------------------------------------------------
create table if not exists public.demo_events (
  id             bigint generated by default as identity primary key,
  session_id     uuid references public.demo_sessions (id) on delete cascade,
  participant_id uuid references public.demo_participants (id) on delete cascade,
  event_type     text not null,
  payload        jsonb not null default '{}',
  created_at     timestamptz default now()
);

-- ----------------------------------------------------------------------------
-- Helpful indexes
-- ----------------------------------------------------------------------------
create index if not exists idx_demo_participants_session_id
  on public.demo_participants (session_id);

create index if not exists idx_demo_harvester_answers_session_id
  on public.demo_harvester_answers (session_id);

create index if not exists idx_demo_survey_responses_session_id
  on public.demo_survey_responses (session_id);

create index if not exists idx_demo_events_session_id_created_at
  on public.demo_events (session_id, created_at);

-- ----------------------------------------------------------------------------
-- Row Level Security
--
-- !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  WARNING  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
-- !! The policies below are WIDE OPEN BY DESIGN: anyone holding the anon  !!
-- !! key can SELECT / INSERT / UPDATE every row in these 5 tables (and    !!
-- !! DELETE demo_sessions). This is acceptable ONLY for a throwaway,      !!
-- !! short-lived event demo with non-sensitive data.                      !!
-- !! DO NOT copy these policies into any production project.             !!
-- !! Delete or rotate the Supabase project after the event.              !!
-- !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
-- ----------------------------------------------------------------------------
alter table public.demo_sessions          enable row level security;
alter table public.demo_participants      enable row level security;
alter table public.demo_harvester_answers enable row level security;
alter table public.demo_survey_responses  enable row level security;
alter table public.demo_events            enable row level security;

-- demo_sessions ---------------------------------------------------------------
drop policy if exists "demo_sessions open select" on public.demo_sessions;
create policy "demo_sessions open select"
  on public.demo_sessions for select
  to anon, authenticated
  using (true);

drop policy if exists "demo_sessions open insert" on public.demo_sessions;
create policy "demo_sessions open insert"
  on public.demo_sessions for insert
  to anon, authenticated
  with check (true);

drop policy if exists "demo_sessions open update" on public.demo_sessions;
create policy "demo_sessions open update"
  on public.demo_sessions for update
  to anon, authenticated
  using (true)
  with check (true);

-- Delete allowed on demo_sessions (admin cleanup; cascades to children)
-- and on all child tables (the admin console's "Reset All" wipes a session's
-- participants/answers/surveys/events without deleting the session itself).
drop policy if exists "demo_sessions open delete" on public.demo_sessions;
create policy "demo_sessions open delete"
  on public.demo_sessions for delete
  to anon, authenticated
  using (true);

drop policy if exists "demo_participants open delete" on public.demo_participants;
create policy "demo_participants open delete"
  on public.demo_participants for delete
  to anon, authenticated
  using (true);

drop policy if exists "demo_harvester_answers open delete" on public.demo_harvester_answers;
create policy "demo_harvester_answers open delete"
  on public.demo_harvester_answers for delete
  to anon, authenticated
  using (true);

drop policy if exists "demo_survey_responses open delete" on public.demo_survey_responses;
create policy "demo_survey_responses open delete"
  on public.demo_survey_responses for delete
  to anon, authenticated
  using (true);

drop policy if exists "demo_events open delete" on public.demo_events;
create policy "demo_events open delete"
  on public.demo_events for delete
  to anon, authenticated
  using (true);

-- demo_participants -----------------------------------------------------------
drop policy if exists "demo_participants open select" on public.demo_participants;
create policy "demo_participants open select"
  on public.demo_participants for select
  to anon, authenticated
  using (true);

drop policy if exists "demo_participants open insert" on public.demo_participants;
create policy "demo_participants open insert"
  on public.demo_participants for insert
  to anon, authenticated
  with check (true);

drop policy if exists "demo_participants open update" on public.demo_participants;
create policy "demo_participants open update"
  on public.demo_participants for update
  to anon, authenticated
  using (true)
  with check (true);

-- demo_harvester_answers ------------------------------------------------------
drop policy if exists "demo_harvester_answers open select" on public.demo_harvester_answers;
create policy "demo_harvester_answers open select"
  on public.demo_harvester_answers for select
  to anon, authenticated
  using (true);

drop policy if exists "demo_harvester_answers open insert" on public.demo_harvester_answers;
create policy "demo_harvester_answers open insert"
  on public.demo_harvester_answers for insert
  to anon, authenticated
  with check (true);

drop policy if exists "demo_harvester_answers open update" on public.demo_harvester_answers;
create policy "demo_harvester_answers open update"
  on public.demo_harvester_answers for update
  to anon, authenticated
  using (true)
  with check (true);

-- demo_survey_responses -------------------------------------------------------
drop policy if exists "demo_survey_responses open select" on public.demo_survey_responses;
create policy "demo_survey_responses open select"
  on public.demo_survey_responses for select
  to anon, authenticated
  using (true);

drop policy if exists "demo_survey_responses open insert" on public.demo_survey_responses;
create policy "demo_survey_responses open insert"
  on public.demo_survey_responses for insert
  to anon, authenticated
  with check (true);

drop policy if exists "demo_survey_responses open update" on public.demo_survey_responses;
create policy "demo_survey_responses open update"
  on public.demo_survey_responses for update
  to anon, authenticated
  using (true)
  with check (true);

-- demo_events -----------------------------------------------------------------
drop policy if exists "demo_events open select" on public.demo_events;
create policy "demo_events open select"
  on public.demo_events for select
  to anon, authenticated
  using (true);

drop policy if exists "demo_events open insert" on public.demo_events;
create policy "demo_events open insert"
  on public.demo_events for insert
  to anon, authenticated
  with check (true);

drop policy if exists "demo_events open update" on public.demo_events;
create policy "demo_events open update"
  on public.demo_events for update
  to anon, authenticated
  using (true)
  with check (true);

-- ----------------------------------------------------------------------------
-- Realtime: add tables to the supabase_realtime publication.
-- Each statement is wrapped in a DO block that swallows duplicate_object so
-- re-running this script never fails. (Realtime is a bonus — the apps always
-- poll as a fallback, so nothing breaks if Realtime is disabled.)
-- ----------------------------------------------------------------------------
do $$
begin
  alter publication supabase_realtime add table public.demo_sessions;
exception
  when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.demo_participants;
exception
  when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.demo_harvester_answers;
exception
  when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.demo_survey_responses;
exception
  when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.demo_events;
exception
  when duplicate_object then null;
end $$;

-- ----------------------------------------------------------------------------
-- Verification: run the query below to confirm all 5 tables exist.
--
--   select table_name
--   from information_schema.tables
--   where table_schema = 'public'
--     and table_name in ('demo_sessions', 'demo_participants',
--                        'demo_harvester_answers', 'demo_survey_responses',
--                        'demo_events')
--   order by table_name;
--
-- Expected: 5 rows. You can also check the policies with:
--
--   select tablename, policyname, cmd
--   from pg_policies
--   where schemaname = 'public' and tablename like 'demo_%'
--   order by tablename, cmd;
-- ----------------------------------------------------------------------------
